version: '2'

services:
    odrecorderh264-cid111:
           image: seresearch/opendlv-on-opendlv-core-on-opendavinci-on-base-dev:latest
           network_mode: host
           volumes:
           - ~/Recordings:/opt/Recordings
           working_dir: "/opt/Recordings"
           ipc: host
           user: odv
           depends_on:
               - odsupercomponent
           command: "/opt/od4/bin/odrecorderh264 --cid=111"

    odsupercomponent:
            image: seresearch/opendlv-cfsd18-on-opendlv-lynx-on-opendlv-on-opendlv-core-on-opendavinci-on-base:latest
            network_mode: "host"
            volumes:
            - .:/opt/opendlv.data
            command: "/opt/od4/bin/odsupercomponent --cid=111 --verbose=0 --configuration=/opt/opendlv.data/configuration"
